#!/usr/bin/env bash

aws s3 cp template.yaml s3://YOUR_BUCKET_NAME/template.yaml

aws cloudformation create-stack \
    --region us-east-1 \
    --stack-name YOUR_STACK_NAME \
    --template-url https://YOUR_BUCKET_NAME.s3.amazonaws.com/template.yaml \
    --parameters ParameterKey=VpcId,ParameterValue=YOUR_VPC_ID